-- EJECUTA ESTE SCRIPT EN EL "SQL EDITOR" DE TU PROYECTO EN SUPABASE

-- 1. Tabla de Ciudades
CREATE TABLE cities (
    name TEXT PRIMARY KEY
);

-- 2. Tabla de Usuarios
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE,
    fullName TEXT,
    password TEXT,
    role TEXT,
    organization TEXT,
    city TEXT
);

-- 3. Tabla de Sellos
CREATE TABLE seals (
    id TEXT PRIMARY KEY,
    type TEXT,
    status TEXT,
    creationDate TEXT,
    lastMovement TEXT,
    entryUser TEXT,
    orderNumber TEXT,
    containerId TEXT,
    notes TEXT,
    city TEXT
);

-- 4. Tabla de Historial
CREATE TABLE history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sealId TEXT REFERENCES seals(id) ON DELETE CASCADE,
    date TEXT,
    fromStatus TEXT,
    toStatus TEXT,
    user TEXT,
    details TEXT
);

-- 5. Tabla de Configuración
CREATE TABLE settings (
    id INTEGER PRIMARY KEY DEFAULT 1,
    title TEXT,
    logo TEXT,
    sealTypes JSONB,
    themeColor TEXT,
    CONSTRAINT single_row CHECK (id = 1)
);

-- Datos iniciales
INSERT INTO cities (name) VALUES ('BOGOTÁ'), ('MEDELLÍN'), ('CALI'), ('BARRANQUILLA');

INSERT INTO users (id, username, fullName, password, role, organization, city)
VALUES ('1', 'admin', 'Administrador Maestro', 'admin', 'ADMIN', 'Compañia Nacional de Chocolates', 'BOGOTÁ');

INSERT INTO settings (id, title, logo, sealTypes, themeColor)
VALUES (1, 'GESTION DE SELLOS CNCH', 'https://chocolates.com.co/wp-content/uploads/2021/04/logo-cnch.png', '["Botella", "Cable", "Plástico", "Metálico"]', '#003594');
